version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: docker/ollama/Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: screen-analysis
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - PYTHONUNBUFFERED=1
    volumes:
      - ./screen_analysis:/app/screen_analysis
      - ./static:/app/static
      - ./templates:/app/templates


networks:
  app-network:
    driver: bridge
    # Enable IPV6
    enable_ipv6: false
    # Additional network settings
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  ollama_data:
    name: screen-analysis_ollama_data
