version: '3.8'

services:
  app:
    volumes:
      - ./screen_analysis:/app/screen_analysis
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - DEBUG=1
      - RELOAD=1
    command: >
      sh -c "uvicorn screen_analysis.main:app --host 0.0.0.0 --port 8000 --reload"
