version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: docker/ollama/Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["usr/bin/bash", "/pull_model.sh"]

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: screen-analysis
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./templates:/app/templates

volumes:
  ollama_data:
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - app-network
  #   depends_on:
  #     - app

networks:
  app-network:
    driver: bridge
    # Enable IPV6
    enable_ipv6: false
    # Additional network settings
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  ollama_data:
    name: screen-analysis_ollama_data
